### ISSUE TITLE
Broken +use client prediction in AG on HL25 build

### ISSUE THREAD

**Issue by execut4ble** [tmp64/BugfixedHL-Rebased#247]
HL25 update changed how +use works so that it no longer "sticks" you to the ground, instead there's a more gradual slowdown.

In AG, however, we still have the old behavior, so there's a small jitter on +use since the client doesn't predict the instant slowdown.

**Comment by fatchiiii** [comment]
yes i think i have this bug

**Comment by tmp64** [comment]
The client can now auto-detect which +use slowdown method to use

**Comment by fatchiiii** [comment]
Nice thank you tmp64 Its possible to create a hardcore bot on the client ?  Have a nice day  Envoyé à partir de Courrier pour Windows De : tmp64Envoyé le :dimanche 6 octobre 2024 09:51À : tmp64/BugfixedHL-RebasedCc : fatchiiii; CommentObjet :Re: [tmp64/BugfixedHL-Rebased] Broken +use client prediction in AG on HL25 build (Issue #247) The client can now auto-detect which +use slowdown method to use—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>
