### ISSUE TITLE
Weird behaviour in spectator mode (Free-Look)

### ISSUE THREAD

**Issue by gundogfan** [tmp64/BugfixedHL-Rebased#39]
When moving in any direction in free look it goes back a bit. For example, pressing +moveleft it does +moveleft but it seems as if right when you release the key it does a short +moveright. It's the same with +forward and +back.

> ] version
> Protocol version 48
> Exe version 1.1.2.1 (valve)
> Exe build: 16:05:41 Jun 15 2009 (4554)

> ] about
> BugfixedHL-Rebased
> Bugfixed and improved Half-Life Client
> Version: 1.6.0-beta2+master.f40c7e6
> Engine: 1.1.2.1,48,4554

**Comment by tmp64** [comment]
Fixed, thanks!

This was caused by mathlib's `VectorNormalize` returning non-zero length for null vectors. This meant that in `PM_SpectatorMove` return condition is always false.

```cpp
wishspeed = VectorNormalize(wishdir);
addspeed = wishspeed - currentspeed;
if (addspeed <= 0)
  return;
```

Client would continue flying forward until velocity has dropped to zero by friction but server would update the position to one when movement keys were released.

**Comment by gundogfan** [comment]
Got it, thanks for the explanation. Good job!
